import React, {FC} from "react";

export default function Search() {

    return (
        <div className={"_pt-10"}>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur fugit molestias mollitia odio pariatur sunt ullam? Alias deleniti deserunt dolor enim esse, excepturi magnam molestias neque nesciunt nulla repudiandae sint!</p>







        </div>
    )
}
